services:
  webserver:
    container_name: webserver
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: always
    stdin_open: true  # Mantener el STDIN abierto para bash
    tty: true         # Asignar una terminal para que bash funcione correctamente
    volumes:
      - .:/ws
