.TH "websrv/srcs Directory Reference" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/srcs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBparse\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClientData\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgeneral_helpers\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhttp_request_helper\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHttpAutoIndex\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHttpCGIHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHttpMultipartHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHttpRangeHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHttpRequestHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHttpResponseHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLogger\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain_hardcode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBServerManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSocketHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwebserver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBWebServerResponseHandler\&.cpp\fP"
.br
.in -1c
