.TH "websrv/inc Directory Reference" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClientData\&.hpp\fP"
.br
.ti -1c
.RI "file \fBhttp_enum_codes\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHttpAutoIndex\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHttpCGIHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHttpMultipartHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHttpRangeHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHttpRequestHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHttpResponseHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLogger\&.hpp\fP"
.br
.ti -1c
.RI "file \fBServerManager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSocketHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBwebserver\&.hpp\fP"
.br
.ti -1c
.RI "file \fBWebserverCache\&.hpp\fP"
.br
.ti -1c
.RI "file \fBWebserverException\&.hpp\fP"
.br
.ti -1c
.RI "file \fBWebServerResponseHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBws_general_defines\&.hpp\fP"
.br
.ti -1c
.RI "file \fBws_permissions_bitwise\&.hpp\fP"
.br
.ti -1c
.RI "file \fBws_structs\&.hpp\fP"
.br
.in -1c
