.TH "CommandPair" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandPair
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <webserver\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBcommand\fP"
.br
.ti -1c
.RI "void(* \fBfunction\fP )(std::vector< std::string >::iterator &, \fBLogger\fP *, \fBLocationConfig\fP &)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const char* CommandPair::command"

.SS "void(* CommandPair::function) (std::vector< std::string >::iterator &, \fBLogger\fP *, \fBLocationConfig\fP &)"


.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
