.TH "e_chunk" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
e_chunk
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <HttpRequestHandler\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "std::string \fBchunk\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::string e_chunk::chunk"

.SS "size_t e_chunk::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
