.TH "websrv/inc/HttpRangeHandler.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/HttpRangeHandler.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'WebServerResponseHandler\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHttpRangeHandler\fP"
.br
.RI "Manages HTTP requests that include range-specific content, such as partial file downloads\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRRH_NAME\fP   'HttpRangeHandler'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RRH_NAME   'HttpRangeHandler'"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
