.TH "websrv/inc/HttpCGIHandler.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/HttpCGIHandler.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'WebServerResponseHandler\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHttpCGIHandler\fP"
.br
.RI "Handles HTTP requests that require CGI script execution\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCGI_NAME\fP   'HttpCGIHandler'"
.br
.ti -1c
.RI "#define \fBCGI_TIMEOUT\fP   5000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CGI_NAME   'HttpCGIHandler'"

.SS "#define CGI_TIMEOUT   5000"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
