.TH "HttpResponseHandler" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HttpResponseHandler \- Manages HTTP responses, with support for caching static file content\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <HttpResponseHandler\&.hpp>\fP
.PP
Inherits \fBWsResponseHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHttpResponseHandler\fP (const \fBLocationConfig\fP *location, const \fBLogger\fP *log, \fBClientData\fP *client_data, \fBs_request\fP &request, int fd)"
.br
.RI "Constructs an \fR\fBHttpResponseHandler\fP\fP instance for handling HTTP responses\&. "
.ti -1c
.RI "void \fBget_file_content\fP (std::string &path)"
.br
.RI "Retrieves the content of a file, utilizing the cache if available\&. "
.ti -1c
.RI "void \fBget_file_content\fP (int pid, int(&fd)[2])"
.br
.RI "Placeholder for retrieving file content using process ID and file descriptor array\&. "
.in -1c

Public Member Functions inherited from \fBWsResponseHandler\fP
.in +1c
.ti -1c
.RI "\fBWsResponseHandler\fP (const \fBLocationConfig\fP *location, const \fBLogger\fP *log, \fBClientData\fP *client_data, \fBs_request\fP &request, int fd)"
.br
.RI "Constructs a \fR\fBWsResponseHandler\fP\fP to manage web server responses\&. "
.ti -1c
.RI "virtual \fB~WsResponseHandler\fP ()"
.br
.RI "Destructor for the \fR\fBWsResponseHandler\fP\fP class\&. "
.ti -1c
.RI "virtual bool \fBhandle_request\fP ()"
.br
.RI "Handles the incoming HTTP request based on the request method\&. "
.ti -1c
.RI "bool \fBsend_error_response\fP ()"
.br
.RI "Sends an HTTP error response to the client, using a custom error page if available\&. "
.ti -1c
.RI "bool \fBredirection\fP ()"
.br
.RI "Handles HTTP redirection for the current request\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBWsResponseHandler\fP
.in +1c
.ti -1c
.RI "virtual bool \fBhandle_get\fP ()"
.br
.RI "Handles HTTP GET requests, validating access, resource data, and sending a response\&. "
.ti -1c
.RI "virtual bool \fBhandle_post\fP ()"
.br
.RI "Handles HTTP POST requests, validating access, saving data, and sending a response\&. "
.ti -1c
.RI "bool \fBhandle_delete\fP ()"
.br
.RI "Handles HTTP DELETE requests by checking permissions and deleting the specified resource\&. "
.ti -1c
.RI "virtual bool \fBvalidate_payload\fP ()"
.br
.RI "Validates the payload of an HTTP request to ensure it meets requirements\&. "
.ti -1c
.RI "bool \fBsave_file\fP (const std::string &save_path, const std::string &content)"
.br
.RI "Saves the provided content to a specified file path\&. "
.ti -1c
.RI "virtual std::string \fBheader\fP (int code, size_t content_size, std::string mime)"
.br
.RI "Constructs an HTTP response header based on provided parameters\&. "
.ti -1c
.RI "virtual bool \fBsend_response\fP (const std::string &body, const std::string &path)"
.br
.RI "Sends an HTTP response with the specified body content and inferred MIME type\&. "
.ti -1c
.RI "bool \fBsender\fP (const std::string &body)"
.br
.RI "Sends the HTTP response to the client through the socket file descriptor\&. "
.ti -1c
.RI "std::string \fBdefault_plain_error\fP ()"
.br
.RI "Generates a default HTML error page for the HTTP response\&. "
.ti -1c
.RI "void \fBturn_off_sanity\fP (\fBe_http_sts\fP status, std::string detail)"
.br
.RI "Disables further request processing by marking the request as invalid\&. "
.in -1c

Protected Attributes inherited from \fBWsResponseHandler\fP
.in +1c
.ti -1c
.RI "const \fBLocationConfig\fP * \fB_location\fP"
.br
.ti -1c
.RI "const \fBLogger\fP * \fB_log\fP"
.br
.ti -1c
.RI "\fBClientData\fP * \fB_client_data\fP"
.br
.ti -1c
.RI "\fBs_request\fP & \fB_request\fP"
.br
.ti -1c
.RI "\fBs_content\fP \fB_response_data\fP"
.br
.ti -1c
.RI "std::string \fB_headers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages HTTP responses, with support for caching static file content\&. 

The \fR\fBHttpResponseHandler\fP\fP class extends \fR\fBWsResponseHandler\fP\fP to handle HTTP responses, utilizing a caching mechanism to optimize retrieval of static files\&. It checks for content in the cache before loading from disk, reducing redundant I/O operations and improving response times for frequently requested resources\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HttpResponseHandler::HttpResponseHandler (const \fBLocationConfig\fP * location, const \fBLogger\fP * log, \fBClientData\fP * client_data, \fBs_request\fP & request, int fd)"

.PP
Constructs an \fR\fBHttpResponseHandler\fP\fP instance for handling HTTP responses\&. Initializes the response handler with configuration, logging, client data, and the server cache, setting up the necessary components for managing static responses\&.

.PP
\fBParameters\fP
.RS 4
\fIlocation\fP Pointer to the \fR\fBLocationConfig\fP\fP containing the configuration details for the server location\&. 
.br
\fIlog\fP Pointer to the \fR\fBLogger\fP\fP instance to record request and response details\&. 
.br
\fIclient_data\fP Pointer to \fR\fBClientData\fP\fP associated with the client connection\&. 
.br
\fIrequest\fP Reference to the \fR\fBs_request\fP\fP structure containing request details\&. 
.br
\fIfd\fP File descriptor for the client connection\&. 
.br
\fIcache\fP Pointer to the \fR\fBWebServerCache\fP\fP for handling cached responses and resources\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void HttpResponseHandler::get_file_content (int pid, int(&) fd[2])\fR [virtual]\fP"

.PP
Placeholder for retrieving file content using process ID and file descriptor array\&. 
.PP
\fBNote\fP
.RS 4
Unused function 
.RE
.PP

.PP
Implements \fBWsResponseHandler\fP\&.
.SS "void HttpResponseHandler::get_file_content (std::string & path)\fR [virtual]\fP"

.PP
Retrieves the content of a file, utilizing the cache if available\&. Attempts to retrieve the file content from the cache\&. If the content is not cached, it loads the file content from disk using the base \fR\fBWsResponseHandler\fP\fP method\&. If the content is successfully loaded, it is then stored in the cache\&.

.PP
\fBParameters\fP
.RS 4
\fIpath\fP Path to the file whose content is to be retrieved\&. 
.RE
.PP

.PP
Reimplemented from \fBWsResponseHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
