.TH "websrv/inc/HttpResponseHandler.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/HttpResponseHandler.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'WebServerResponseHandler\&.hpp'\fP
.br
\fR#include 'WebserverCache\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHttpResponseHandler\fP"
.br
.RI "Manages HTTP responses, with support for caching static file content\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRHB_NAME\fP   'HttpResponseHandler'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RHB_NAME   'HttpResponseHandler'"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
