.TH "websrv/inc/HttpAutoIndex.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/HttpAutoIndex.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'WebServerResponseHandler\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHttpAutoIndex\fP"
.br
.RI "The \fR\fBHttpAutoIndex\fP\fP class handles the generation of an automatic index for a directory listing\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAI_NAME\fP   'HttpAutoIndex'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AI_NAME   'HttpAutoIndex'"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
