.TH "websrv/srcs/main.cpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/srcs/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br
\fR#include <cstring>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <map>\fP
.br
\fR#include 'webserver\&.hpp'\fP
.br
\fR#include 'ServerManager\&.hpp'\fP
.br
\fR#include <signal\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsignal_handler\fP (int sig)"
.br
.RI "Signal handler to end webserver execution\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Main function - Entry point\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBServerManager\fP * \fBrunning_server\fP = NULL"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main function - Entry point\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP count of arguments\&. 
.br
\fIargv\fP arguments of exec\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBServerManager\fP: That control all the workflow\&. 
.RE
.PP

.SS "void signal_handler (int sig)"

.PP
Signal handler to end webserver execution\&. Due to webserver execution is an endless loop, a handler to close it properly is needed\&. SIGINT, SIGTERM and SIGTSTP are allowed\&.
.PP
\fBParameters\fP
.RS 4
\fIsig\fP Received signal\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "\fBServerManager\fP* running_server = NULL"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
