.TH "websrv/srcs/parse/parse_location.cpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/srcs/parse/parse_location.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'webserver\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparse_location_index\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_location_error_page\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_root\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_autoindex\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_cgi\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_template_error_page\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_accept_only\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.ti -1c
.RI "void \fBparse_redirection\fP (std::vector< std::string >::iterator &it, \fBLogger\fP *logger, \fBLocationConfig\fP &location)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void parse_accept_only (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_autoindex (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_cgi (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_location_error_page (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_location_index (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_redirection (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_root (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SS "void parse_template_error_page (std::vector< std::string >::iterator & it, \fBLogger\fP * logger, \fBLocationConfig\fP & location)"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
