.TH "s_cgi" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_cgi \- Represents metadata for a CGI (Common Gateway Interface) request\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ws_structs\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBs_cgi\fP (std::string cp, std::string s)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBcgi_path\fP"
.br
.ti -1c
.RI "std::string \fBscript\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents metadata for a CGI (Common Gateway Interface) request\&. 

This structure contains information about the path to the CGI executable and the script being executed\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "s_cgi::s_cgi (std::string cp, std::string s)\fR [inline]\fP"

.SH "Field Documentation"
.PP 
.SS "std::string s_cgi::cgi_path"

.SS "std::string s_cgi::script"


.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
