.TH "websrv/inc/WebserverCache.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/WebserverCache.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <map>\fP
.br
\fR#include <list>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWebServerCache< T >\fP"
.br
.RI "A simple, in-memory Least Recently Used (LRU) cache\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
