.TH "websrv/inc/WebserverException.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/WebserverException.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <exception>\fP
.br
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWebServerException\fP"
.br
.RI "Custom exception class for handling errors within the web server project\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
