.TH "websrv/inc/ws_general_defines.hpp" 3 "WebServer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
websrv/inc/ws_general_defines.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBASIC_STYLE\fP"
.br
.ti -1c
.RI "#define \fBERROR_STYLE\fP   'h1 {font\-size: 3em;margin\-bottom: 10px;color: #e74c3c;}h2 {border\-top: 1px solid #9f9f9f;font\-size: 1\&.5em;padding: 10px;color: #555;}'"
.br
.ti -1c
.RI "#define \fBAUTOINDEX_STYLE\fP"
.br
.ti -1c
.RI "#define \fBFOOTER_STYLE\fP"
.br
.ti -1c
.RI "#define \fBSVG_LOGO\fP"
.br
.ti -1c
.RI "#define \fBFOOTER_GENERAL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUTOINDEX_STYLE"
\fBValue:\fP.PP
.nf
"h1\&.autoindex {font\-size: 3em;margin\-bottom: 10px;color: #403b3b;}\\n" \\
"table {width: 90%;margin: 20px auto;border\-collapse: collapse;background\-color: #ffffff;box\-shadow: 0px 4px 8px rgba(0, 0, 0, 0\&.1);}\\n" \\
"th, td {padding: 15px;text\-align: left;border\-bottom: 1px solid #9f9f9f;}\\n" \\
"th {background\-color: #98bafc;color: #000000;font\-weight: bold;}\\n" \\
"tr:hover {background\-color: #f1f1f1;}\\n" \\
"a {color: #3498db;text\-decoration: none;}\\n"
.fi

.SS "#define BASIC_STYLE"
\fBValue:\fP.PP
.nf
"* { margin: 0; padding: 0; box\-sizing: border\-box;}\\n" \\
"body {height: 100vh;display: flex;justify\-content: center;align\-items: center;font\-family: Arial, sans\-serif;background\-color: #f8ffff;color: #333;}\\n" \\
"div {text\-align: center; width: 100%;}\\n"
.fi

.SS "#define ERROR_STYLE   'h1 {font\-size: 3em;margin\-bottom: 10px;color: #e74c3c;}h2 {border\-top: 1px solid #9f9f9f;font\-size: 1\&.5em;padding: 10px;color: #555;}'"

.SS "#define FOOTER_GENERAL"
\fBValue:\fP.PP
.nf
"<footer>" \\
SVG_LOGO \\
"<span>Powered by WebServer</span></footer>"
.fi

.SS "#define FOOTER_STYLE"
\fBValue:\fP.PP
.nf
"footer {padding: 5px;border\-top: solid 1px #9f9f9f;width: 100vw;min\-height: 100px;text\-align: center;position: absolute;bottom: 10px;}\\n" \\
"footer > span {width: 100%;display: block;}\\n" \\
"footer > svg {width: 100px;height: auto;justify\-content: center;}"
.fi

.SS "#define SVG_LOGO"

.SH "Author"
.PP 
Generated automatically by Doxygen for WebServer from the source code\&.
