services:
  webserver:
    container_name: webserver
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"

    restart: always
    stdin_open: true  # Keep STDIN open to use bash
    tty: true         # Assing a terminal to bash
#    volumes:
#      - .:/ws
    environment:
      WEBSERVER_PATH: $WEBSERVER_PATH
